fortunes:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /fortunes/
        permanent: true
#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number
